CREATE DATABASE IF NOT EXISTS MonitorInputDevice;

USE MonitorInputDevice;

CREATE TABLE IF NOT EXISTS Log(
	Time CHAR(36) PRIMARY KEY,
	IP VARCHAR(15) NOT NULL,
	Port VARCHAR(5) NOT NULL,
	Request TEXT NOT NULL,
	Response LONGTEXT,
    ResponseTime CHAR(36)
);

CREATE TABLE IF NOT EXISTS User(
	ID CHAR(36) PRIMARY KEY,
	UserName VARCHAR(32) UNIQUE NOT NULL,
	Password CHAR(32) NOT NULL,
	TokenID CHAR(36) DEFAULT '',
	TokenExpiryTime CHAR(36) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS KeyPressingEvent(
	ID CHAR(36) PRIMARY KEY,
	UserID CHAR(36) NOT NULL,
	Time CHAR(36) NOT NULL,
	KeyName VARCHAR(64) NOT NULL,
	Status TINYINT NOT NULL
);

CREATE TABLE IF NOT EXISTS MouseMovingEvent(
	ID CHAR(36) PRIMARY KEY,
	UserID CHAR(36) NOT NULL,
	Time CHAR(36) NOT NULL,
    OriginalPosition VARCHAR(16) NOT NULL,
    NewPosition VARCHAR(16) NOT NULL
);